# ███╗░░██╗███████╗██╗░░██╗██╗░░░██╗░██████╗
# ████╗░██║██╔════╝╚██╗██╔╝██║░░░██║██╔════╝
# ██╔██╗██║█████╗░░░╚███╔╝░██║░░░██║╚█████╗░
# ██║╚████║██╔══╝░░░██╔██╗░██║░░░██║░╚═══██╗
# ██║░╚███║███████╗██╔╝╚██╗╚██████╔╝██████╔╝
# ╚═╝░░╚══╝╚══════╝╚═╝░░╚═╝░╚═════╝░╚═════╝░

# Discord server: https://discord.gg/p7cxhw7E2M
# Modrinth: https://modrinth.com/plugin/nexuss

# Set the locale for all messages.
# You can see all available locales in the `language` folder.
language: en

# You can enable or disable all Nexus commands.
commands:
  anvil:
    enable: true
  back:
    enable: true
  broadcast:
    enable: true
  cartography:
    enable: true
  enderchest:
    enable: true
  fly:
    enable: true
  gamemode:
    enable: true
  give:
    enable: true
  god:
    enable: true
  grindstone:
    enable: true
  hat:
    enable: true
  heal:
    enable: true
  home:
    enable: true
  invsee:
    enable: true
  loom:
    enable: true
  message:
    enable: true
  ping:
    enable: true
  repair:
    enable: true
  smithingtable:
    enable: true
  speed:
    enable: true
  spit:
    enable: true
  day:
    enable: true
  tp:
    enable: true
  tphere:
    enable: true
  tpposition:
    enable: true
  vanish:
    enable: true
  warp:
    enable: true
  whois:
    enable: true
  workbench:
    enable: true

# You can enable or disable all Nexus features.
features:
  glass-knocking:
    enable: true
  door-knocking:
    enable: true
  book-formatting:
    enable: true
  sign-formatting:
    enable: true
  join-message:
    enable: true
  quit-message:
    enable: true

# You can configure sounds that will be played when a player uses commands.
# Format: "SOUND_NAME:VOLUME:PITCH"
sound:
  glass-knocking:
    enable: true
    type: "BLOCK_GLASS_BREAK:1:1"
  door-knocking:
    enable: true
    type: "BLOCK_WOOD_PLACE:1:1"
  spit:
    enable: true
    type: "ENTITY_LLAMA_SPIT:0.3:1"
  heal:
    enable: true
    type: "ENTITY_EXPERIENCE_ORB_PICKUP:1:1"
  home:
    enable: true
    type: "ENTITY_ENDERMAN_TELEPORT:1:1"
  warp:
    enable: true
    type: "ENTITY_ENDERMAN_TELEPORT:1:1"
  join:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  quit:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  tphere:
    enable: true
    type: "ENTITY_ENDERMAN_TELEPORT:1:1"
  tpup:
    enable: true
    type: "ENTITY_ENDERMAN_TELEPORT:1:1"
  tpall:
    enable: true
    type: "ENTITY_ENDERMAN_TELEPORT:1:1"
  tp:
    enable: true
    type: "ENTITY_ENDERMAN_TELEPORT:1:1"
  tppos:
    enable: true
    type: "ENTITY_ENDERMAN_TELEPORT:1:1"
  back:
    enable: true
    type: "ENTITY_ENDERMAN_TELEPORT:1:1"

# DO NOT CHANGE THIS!
version: 0.1