name: Nexus
version: '${version}'
main: space.bxteam.nexus.Nexus
api-version: '1.16'
authors: [ NONPLAYT, XENOLIT ]
description: Nexus gives you ability to personalize your Minecraft server with useful features
website: https://nexus.bxteam.gq
soft-depend: [ PlaceholderAPI ]
commands:
  nexus:
    aliases:
      - ns
      - nx
    permission: nexus.command.nexus
permissions:
  nexus.admin:
    default: op
  nexus.bypass.fullserver:
    default: op