name: Nexus
version: '${version}'
main: gq.bxteam.nexus.Nexus
api-version: '1.16'
authors: [ NONPLAYT, Xenolit ]
description: Nexus gives you ability to personalize your Minecraft server with useful features
website: https://nexus.bxteam.gq
commands:
  gamemode:
    aliases:
      - gm
      - gms
      - gmc
      - gma
      - gmsp
    permission: nexus.command.gamemode
  heal:
    permission: nexus.command.heal
  nexus:
    aliases:
      - ns
      - nx
    permission: nexus.user
permissions:
  nexus.command.gamemode:
    default: op
  nexus.command.heal:
    default: op
  nexus.user:
    default: true