name: Nexus
version: '${version}'
main: gq.bxteam.nexus.Nexus
api-version: '1.16'
authors: [ NONPLAYT, XENOLIT ]
description: Nexus gives you ability to personalize your Minecraft server with useful features
website: https://nexus.bxteam.gq
commands:
  anvil:
    permission: nexus.command.anvil
  cartography:
    permission: nexus.command.cartography
  enderchest:
    aliases:
      - ec
    permission: nexus.command.enderchest
  fly:
    permission: nexus.command.fly
  gamemode:
    aliases:
      - gm
      - gms
      - gmc
      - gma
      - gmsp
    permission: nexus.command.gamemode
  god:
    permission: nexus.command.god
  grindstone:
    permission: nexus.command.grindstone
  hat:
    permission: nexus.command.hat
  heal:
    permission: nexus.command.heal
  invsee:
    aliases:
      - inv
      - inventory
    permission: nexus.command.invsee
  loom:
    permission: nexus.command.loom
  message:
    aliases:
      - msg
      - m
    permission: nexus.command.msg
  nexus:
    aliases:
      - ns
      - nx
    permission: nexus.command.nexus
  ping:
    permission: nexus.command.ping
  speed:
    permission: nexus.command.speed
  teleport:
    aliases:
      - tp
    permission: nexus.command.teleport
  teleportpos:
    aliases:
      - tppos
    permission: nexus.command.teleportpos
  day:
    aliases:
      - night
      - noon
      - midnight
    permission: nexus.command.time
  penis:
    permission: nexus.command.penis
  workbench:
    aliases:
      - wb
      - craft
    permission: nexus.command.workbench
permissions:
  nexus.admin:
    default: op
  nexus.command.penis:
    default: op