[versions]
minecraft = "1.19.4-R0.1-SNAPSHOT"

[plugins]
lombok = { id = "io.freefair.lombok", version = "8.7.1" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
userdev = { id = "io.papermc.paperweight.userdev", version = "1.7.2" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.3.0" }
paperyml = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }

[libraries]
paper = { module = "io.papermc.paper:paper-api", version = "1.19.4-R0.1-SNAPSHOT" }

configlib = { module = "de.exlll:configlib-yaml", version = "4.5.0" }
hikaricp = { module = "com.zaxxer:HikariCP", version = "5.1.0" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version = "3.4.1"}
placeholderapi = { module = "me.clip:placeholderapi", version = "2.11.6" }
litecommands = { module = "dev.rollczi:litecommands-bukkit", version = "3.4.3" }
bstats = { module = "org.bstats:bstats-bukkit", version = "3.0.2" }