CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    player_uuid VARCHAR(255) UNIQUE,
    username VARCHAR(255),
    PreviousLocation VARCHAR(255),
    Homes VARCHAR(255),
    LastReceipt VARCHAR(255),
    Vanished VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS warps (
    id INT AUTO_INCREMENT PRIMARY KEY,
    warp_name VARCHAR(255) NOT NULL,
    x DOUBLE NOT NULL,
    y DOUBLE NOT NULL,
    z DOUBLE NOT NULL,
    pitch FLOAT NOT NULL,
    yaw FLOAT NOT NULL,
    world VARCHAR(255) NOT NULL
);
