# This workflow will build Nexus, then publish it to our repository and create a release with a changelog
name: Deploy Nexus

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        type: string
      pre-release:
        description: 'Is this a pre-release?'
        required: true
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Parse tag
        id: vars
        run: echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Publish API to repository
        continue-on-error: true
        run: ./gradlew nexus-api:publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_SECRET }}

      - name: Create release and changelog
        uses: MC-Machinations/auto-release-changelog@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Nexus ${{ steps.vars.outputs.tag }}
          files: 'nexus-plugin/build/libs/*.jar'
          pre-release: ${{ github.event.inputs.pre-release }}
