# This workflow will build Nexus, then publish it to our repository and create a release with a changelog
name: Deploy Nexus

on:
  release:
    types: [published]

permissions:
  contents: read
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Publish API to Repository
        continue-on-error: true
        run: ./gradlew nexus-api:publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_SECRET }}

      - name: Build Nexus
        run: ./gradlew nexus-plugin:shadowJar

      - name: Publish to Modrinth
        uses: Kira-NT/mc-publish@v3.3.0
        with:
          modrinth-id: '4ut4u8Ay'
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: false

          files: 'nexus-plugin/build/libs/*.jar'

          name: 'Nexus ${{ github.event.release.tag_name }}'
          version: ${{ github.event.release.tag_name }}
          version-type: 'beta'
          changelog: ${{ github.event.release.body }}

          loaders: |
            paper
            purpur
            folia
          game-versions: |
            1.19
            1.19.1
            1.19.2
            1.19.3
            1.19.4
            1.20
            1.20.1
            1.20.2
            1.20.3
            1.20.4
            1.20.5
            1.20.6
            1.21
            1.21.1
            1.21.2
            1.21.4
            1.21.5
          java: 17
