name: Publish Nexus API

on:
  release:
    branches: [ master ]
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Publish with Gradle
        continue-on-error: true
        run: ./gradlew nexus-api:publish -PnexusUsername=${{ secrets.NEXUS_USERNAME }} -PnexusPassword=${{ secrets.NEXUS_PASSWORD }}
